spring:
  redis:
  #连接的数据库索引
    database: 0
    #连接超时时间
    timeout: 100
    #数据库地址
    host: 127.0.0.1
    #端口号
    port: 6379
    #密码默认为空
    password:
    pool:
      #连接池最大连接数
      max-active: 8
      #连接池最大阻塞等待时间，-1为一直等待
      max-wait: -1
      #连接池最大空闲连接
      max-idle: 8
      #连接池最小空闲连接
      min-idle: 0